//******************************************************
//Author:	    Steven Reeves
//Filename:	    Lab2.S
//Date Created:	    4/12/2018
//Modifications:    4/12/2018 - created
//******************************************************

#include <xc.h>
// Use PIC32MX460F512L
// #define statements follow here

.global main

.data
// data segment for READ/WRITE data follows here

.text
.set noreorder
// text segment for instructions and CONSTANT READ-ONLY data follows here
// stored in non-volatile flash memory

.ent main
main:

	// instructions go here

.end main

	// constants go here


